[package]
name = "orbimage"
description = "Orbital image features"
repository = "https://github.com/redox-os/orbimage"
version = "0.1.9"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.2"

[dependencies.jpeg-decoder]
version = "0.1"
optional = true
default-features = false

[dependencies.png]
version = "0.5"
optional = true
default-features = false

[features]
default = ["bmp", "jpg", "png"]
bmp = []
jpg = ["jpeg-decoder"]
